name: 📝 Docs
description: 코드 또는 애플리케이션과 관련한 문서를 작성합니다.
title: "[DOCS] "
labels:
  - 📝 docs
body:
  - type: markdown
    attributes:
      value: |
        ---
        ### 이슈를 작성하기 전에 아래 내용을 확인해주세요:
        - 동일한 작업에 대한 이슈가 없음을 확인했습니다.
        - 작업 목적이 명확합니다.

  - type: textarea
    id: task-description
    attributes:
      label: 📄 작성할 문서 개요
      description: 문서를 왜 작성하는지, 어떤 내용인지 설명해주세요.
      placeholder: |
        ex) JWT 관련 API를 메모하기 위해 문서를 작성합니다.
        - `/jwt_api.md`
    validations:
      required: true

  - type: textarea
    id: task-steps
    attributes:
      label: 📈 진행 체크리스트
      description: 어떤 작업을 진행할지 체크리스트 형식으로 작성해주세요. (선택 사항)
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2

  - type: textarea
    id: additional-context
    attributes:
      label: 👍🏻 추가 정보
      description: 작업을 이해하는 데 도움이 될 스크린샷, 첨부파일, 링크 등 추가 정보를 작성해주세요. (선택 사항)

  - type: markdown
    attributes:
      value: |
        ---
        ### 이슈를 생성하기 전에 아래 내용을 확인해주세요:
        - 제목이 작업의 내용을 잘 표현하고 있습니다.
        - 작업자를 지정했습니다.
        - Label이 단 하나만 선택되어 있습니다.
        - 프로젝트를 연결했습니다.