name: π™‹π» Question
description: μ½”λ“ λλ” μ§„ν–‰ λ°©ν–¥ λ“± κ¶κΈν• λ‚΄μ©μ„ μ§λ¬Έν•©λ‹λ‹¤.
title: "[QUESTION] "
labels:
  - π™‹π» question
body:
  - type: markdown
    attributes:
      value: |
        ---
        ### μ΄μλ¥Ό μ‘μ„±ν•κΈ° μ „μ— μ•„λ λ‚΄μ©μ„ ν™•μΈν•΄μ£Όμ„Έμ”:
        - λ™μΌν• μ§λ¬Έμ— λ€ν• μ΄μκ°€ μ—†μμ„ ν™•μΈν–μµλ‹λ‹¤.
        - μ§λ¬Έ λ‚΄μ©κ³Ό λ©μ μ΄ λ…ν™•ν•©λ‹λ‹¤.

  - type: textarea
    id: task-description
    attributes:
      label: π“„ μ§λ¬Έ λ‚΄μ©
      description: μ§λ¬Έ λ‚΄μ©μ„ μ‘μ„±ν•΄μ£Όμ„Έμ”.
    validations:
      required: true

  - type: textarea
    id: linked-issue
    attributes:
      label: β›“οΈ κ΄€λ ¨ μ΄μ
      description: μ§λ¬Έκ³Ό κ΄€λ ¨λμ–΄μλ” μ΄μλ¥Ό μ‘μ„±ν•΄μ£Όμ„Έμ”. (μ„ νƒ μ‚¬ν•­)
      placeholder: |
        - #1
        - #2

  - type: textarea
    id: additional-context
    attributes:
      label: π‘π» μ¶”κ°€ μ •λ³΄
      description: μ§λ¬Έμ„ μ΄ν•΄ν•λ” λ° λ„μ›€μ΄ λ  μ¤ν¬λ¦°μƒ·, μ²¨λ¶€νμΌ, λ§ν¬ λ“± μ¶”κ°€ μ •λ³΄λ¥Ό μ‘μ„±ν•΄μ£Όμ„Έμ”. (μ„ νƒ μ‚¬ν•­)

  - type: markdown
    attributes:
      value: |
        ---
        ### μ΄μλ¥Ό μƒμ„±ν•κΈ° μ „μ— μ•„λ λ‚΄μ©μ„ ν™•μΈν•΄μ£Όμ„Έμ”:
        - μ λ©μ΄ μ§λ¬Έμ λ‚΄μ©μ„ μ ν‘ν„ν•κ³  μμµλ‹λ‹¤.
        - λ³ΈμΈκ³Ό μ§λ¬Έ λ€μƒμ„ μ‘μ—…μλ΅ μ§€μ •ν–μµλ‹λ‹¤.
        - Labelμ΄ λ‹¨ ν•λ‚λ§ μ„ νƒλμ–΄ μμµλ‹λ‹¤.
        - ν”„λ΅μ νΈλ¥Ό μ—°κ²°ν–μµλ‹λ‹¤.