name: β™»οΈ Refactor
description: κΈ°λ¥ λ³€ν™” μ—†μ΄ μ½”λ“λ¥Ό μμ •ν•©λ‹λ‹¤. (μ½”λ“ κµ¬μ΅° κ°μ„ , κ°€λ…μ„± ν–¥μƒ λ“±)
title: "[REFACTOR] "
labels:
  - β™»οΈ refactor
body:
  - type: markdown
    attributes:
      value: |
        ---
        ### μ΄μλ¥Ό μ‘μ„±ν•κΈ° μ „μ— μ•„λ λ‚΄μ©μ„ ν™•μΈν•΄μ£Όμ„Έμ”:
        - λ™μΌν• μ‘μ—…μ— λ€ν• μ΄μκ°€ μ—†μμ„ ν™•μΈν–μµλ‹λ‹¤.
        - λ¦¬ν©ν† λ§ μ‚¬μ κ°€ λ…ν™•ν•©λ‹λ‹¤.

  - type: input
    id: task-target
    attributes:
      label: π“„ μ‘μ—… λ€μƒ
      description: λ¬΄μ—‡μ„ λ€μƒμΌλ΅ λ¦¬ν©ν† λ§μ„ μ§„ν–‰ν•  κ²ƒμΈμ§€ μ‘μ„±ν•΄μ£Όμ„Έμ”.
      placeholder: ex) μ‚¬μ©μ μ¶”κ°€ λ΅μ§
    validations:
      required: true

  - type: textarea
    id: task-description
    attributes:
      label: π“„ μ‘μ—… κ°μ”
      description: μ§„ν–‰ ν•  λ¦¬ν©ν† λ§μ— λ€ν• μ΄μ μ™€ μ„¤λ…μ„ μ‘μ„±ν•΄μ£Όμ„Έμ”.
      placeholder: ex) μ½”λ“ κ°€λ…μ„± ν–¥μƒμ„ μ„ν•΄ μ½”λ“λ¥Ό μ •λ¦¬ν•©λ‹λ‹¤.
    validations:
      required: true

  - type: textarea
    id: task-steps
    attributes:
      label: π“ μ§„ν–‰ μ²΄ν¬λ¦¬μ¤νΈ
      description: μ–΄λ–¤ μ‘μ—…μ„ μ§„ν–‰ν• μ§€ μ²΄ν¬λ¦¬μ¤νΈ ν•μ‹μΌλ΅ μ‘μ„±ν•΄μ£Όμ„Έμ”. (μ„ νƒ μ‚¬ν•­)
      placeholder: |
        - [ ] μ‘μ—… 1
        - [ ] μ‘μ—… 2

  - type: textarea
    id: additional-context
    attributes:
      label: π‘π» μ¶”κ°€ μ •λ³΄
      description: μ‘μ—…μ„ μ΄ν•΄ν•λ” λ° λ„μ›€μ΄ λ  μ¤ν¬λ¦°μƒ·, μ²¨λ¶€νμΌ, λ§ν¬ λ“± μ¶”κ°€ μ •λ³΄λ¥Ό μ‘μ„±ν•΄μ£Όμ„Έμ”. (μ„ νƒ μ‚¬ν•­)

  - type: markdown
    attributes:
      value: |
        ---
        ### μ΄μλ¥Ό μƒμ„±ν•κΈ° μ „μ— μ•„λ λ‚΄μ©μ„ ν™•μΈν•΄μ£Όμ„Έμ”:
        - μ λ©μ΄ μ‘μ—…μ λ‚΄μ©μ„ μ ν‘ν„ν•κ³  μμµλ‹λ‹¤.
        - μ‘μ—…μλ¥Ό μ§€μ •ν–μµλ‹λ‹¤.
        - Labelμ΄ λ‹¨ ν•λ‚λ§ μ„ νƒλμ–΄ μμµλ‹λ‹¤.
        - ν”„λ΅μ νΈλ¥Ό μ—°κ²°ν–μµλ‹λ‹¤.